version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - companion-net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - companion-net
    environment:
      - MONGO_URI=mongodb://mongo:27017/companion-ai

networks:
  companion-net:
