version: '3.8'
services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - backend_default
    env_file:
      - .env.test
    command: ["sh", "wait-for-mongo.sh"]

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend_default

networks:
  backend_default:
    driver: bridge
