version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: backend-1
    environment:
      - NODE_ENV=test
    working_dir: /app/backend
    command: npm run test
    volumes:
      - .:/app
      - ./backend/.env.test:/app/backend/.env.test
    depends_on:
      - mongodb
    tty: true

  mongodb:
    image: mongo
    container_name: backend-mongodb-1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
