version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend-net

  backend:
    build: .
    container_name: backend
    depends_on:
      - mongodb
    networks:
      - backend-net
    environment:
      - MONGO_URI=mongodb://mongodb:27017/companion-ai
    command: ["sh", "-c", "./wait-for-mongo.sh && node server.js"]

networks:
  backend-net:
    driver: bridge
